services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.php
  #   # image: php:8.3.4-apache
  #   container_name: php-apache
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./www:/var/www/html
  #   # depends_on:
  #   #   - db

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./wordpress:/var/www/html
      # - wordpress:/var/www/html
    # depends_on:
    #   - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql
volumes:
  # wordpress:
  db:
# source /docker-entrypoint-initdb.d/init.sql
